name: Android APK (Debug) Build

on:
  workflow_dispatch:   # ← Run workflow ボタンで手動実行できる
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Android SDK を用意（cmdline-tools / build-tools / platform を入れる）
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" "cmdline-tools;latest"
          yes | sdkmanager --licenses

      # Gradle が SDK を見つけられるように local.properties を作る
      - name: Write local.properties (SDK path)
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties

      # Gradle 実行（ラッパー無しでも動く方式）
      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.6   # AGP 8.4.0 と相性の良い版
          arguments: assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
